var Localization = {

    'labels': {
        //'TEST': 'TEST'
        "PP_TIT_CONFIRMATION": "Confirmation",
        "PP_LBL_CONFIRMATION_DELETE_ATTACHMENT": "Do you want to delete selected attachment?",
        "PP_LBL_CONFIRMATION_EXCLUDE_PRODUCT": "Do you want to exclude the product?",
        "PP_LBL_CONFIRMATION_REMOVE_EXCLUSION_PRODUCT": "Do you want to remove the exclusion for the product?",
        "PP_LBL_CONFIRMATION_REMOVE_INCLUDED_PRODUCT": "Do you want to remove the manually included product?",
        "PP_TIT_INFORMATION": "Information",
        "PP_LBL_INFORMATION_FUNDS": "There are no funds selected.",
        "PP_LBL_CONFIRMATION_DELETE_FUNDS": "Do you want to delete selected funds?",
        "PP_LBL_FUND_NAME": "Fund Name",
        "PP_LBL_FUND_DESCRIPTION": "Description",
        "PP_LBL_FUND_ANCHOR_CUSTOMER": "Anchor Customer",
        "PP_LBL_FUND_ANCHOR_PRODUCT": "Anchor Product",
        "PP_LBL_FUND_TYPE": "Fund Type",
        "PP_LBL_FUND_AMOUNT": "Amount",
        "PP_LBL_AVAILABLE_TO_SPEND": "Available to Spend",
        "PP_LBL_PERCENTAGE_ALLOCATED": "% Allocated",
        "PP_LBL_AMOUNT_ALLOCATED": "Amount Allocated",
        "PP_TIT_FUNDS": "Funds",
        "PP_TIT_CHILD_PROMOTION_ACCOUNTS": "Child Promotion Accounts",
        "PP_TIT_ACCOUNT": "Account",
        "PP_LBL_CUSTOMER_UNIQUE": "Costumer Unique",
        "PP_LBL_PROMOTION_ID": "Promotion Id",
        "PP_TIT_PUSH_PROMOTION": "Push Promotion",
        "PP_LBL_PUSH_FINALIZED": "Push child promotion accounts finalized",
        "PP_LBL_PUSH_PROCESS_PROGRESS": "Push process progress.",
        "PP_LBL_PROMOTIONS_DONE": "Promotions done",
        "PP_TIT_PROMOTION_SLOGAN": "Promotion slogan",
        "PP_TIT_PUSH_ERROR": "Error pushing child promotion",
        "PP_LBL_PUSH_ERROR": "An error occurred while trying to push the child promotion account",
        "PP_TIT_CLEAN_PUSH_ERROR": "Error cleaning child promotions",
        "PP_LBL_CLEAN_PUSH_ERROR": "An error occurred while trying to clean the child promotions account",
        "PP_TIT_INCLUDE_EXCLUDE_ALL": "Include/Exclude All",
        "PP_TIT_ATTACHMENTS": "Attachments",
        "PP_LBL_IMAGE_DESCRIPTION": "Description",
        "PP_LBL_IMAGE_CREATION_DATE": "Creation Date",
        "PP_LBL_IMAGE_LAST_UPDATE": "Last Update",
        "PP_TIT_UPLOAD_ERROR": "Error Uploading",
        "PP_LBL_UPLOAD_ERROR": "An error occurred while trying to upload the file",
        "PP_LBL_DESCRIPTION": "Description",
        "PP_LBL_ANCHOR_CUSTOMER": "Anchor Customer",
        "PP_LBL_ANCHOR_PRODUCT": "Anchor Product",
        "PP_LBL_AMOUNT": "Amount",
        "PP_LBL_NAME_ATTACHMENT": "Name",
        "PP_LBL_SIZE_ATTACHMENT": "Size",
        "PP_LBL_DESCRIPTION_ATTACHMENT": "Description",
        "PP_LBL_CREATION_DATE_ATTACHMENT": "Creation Date",
        "PP_LBL_LAST_UPDATE_DATE_ATTACHMENT": "Last Update Date",
        "PP_LBL_DRAG_ATTACHMENTS": "Drag attachments here or",
        "PP_LBL_UPLOAD_ATTACHMENTS": "Upload Files",
        "PP_LBL_UPLOADING_ATTACHMENTS": "Uploading...",
        "PP_LBL_IMAGES_ATTACHMENTS": "Images",
        "PP_LBL_VIDEOS_ATTACHMENTS": "Videos",
        "PP_LBL_FILES_ATTACHMENTS": "Files",
        "PP_LBL_NO_ATTACHMENTS_UPLOADED_1": "No Attachments uploaded, yet. Switch to the",
        "PP_LBL_NO_ATTACHMENTS_UPLOADED_2": "to Upload some Files. ",
        "PP_LBL_EDIT_MODE_ATTACHMENTS": "Edit Mode",
        "PP_TIT_UPLOAD_ATTACHMENT_ERROR": "Upload Error",
        "PP_LBL_UPLOAD_ATTACHMENT_SIZE_ERROR": "File incorrect size. The attachment has to be less than 25MB.",
        "PP_LBL_UPLOAD_ATTACHMENT_FILENAME_SIZE_ERROR": "The filename is too long (max. 80 chars)",
        "PP_LBL_UPLOAD_ATTACHMENT_NUMBER_OF_FILES_ERROR": "Only one file allowed per upload",
        "PP_BTN_APPROVE": "Approve",
        "PP_BTN_REJECT": "Reject",
        "PP_BTN_SUBMIT": "Submit",
        "PP_BTN_SAVE": "Save",
        "PP_BTN_PUSH": "Push",
        //PMA - START CODE - 2017-01-13 - Threshold button
        "PP_BTN_INVOKETHRESHOLD": "Threshold",
        //PMA - END CODE - 2017-01-13 - Threshold button
        "PP_BTN_RELEASE": "Release",
        "PP_BTN_MANAGE_TIERS": "Manage Tiers",
        "PP_BTN_APPLY_TIERS": "Apply Tiers",
        "PP_BTN_NEW": "New",
        "PP_TIT_RELEASE_ERROR": "Error updating child promotions",
        "PP_LBL_RELEASE_ERROR": "An error occurred while trying to release the child promotions account",
        "PP_TIT_TIERED_INFORMATION": "Tiered Information",
        "PP_TIT_VOLUME_MIN": "Volume Min",
        "PP_TIT_VOLUME_MAX": "Volume Max",
        "PP_TIT_AMOUNT": "Amount",
        "PP_TIT_SELECT": "SELECT",
        "PP_LBL_NO_TIERS": "No Tiers associated to this tactic",
        //PMA - START CODE - 2017-01-16 - New UK Button
        "PP_BTN_SIMULATION": "Simulation",
        "PP_BTN_MODEL": "Model",
        "PP_BTN_PLANNED": "Planned",
        "PP_BTN_SUBMITTEDFORAPPROVAL": "Submitted for Approval",
        "PP_BTN_REJECTED": "Rejected",
        "PP_BTN_FINALISED": "Finalised",
        "PP_BTN_CANCELLED": "Cancelled",
        "PP_BTN_STOPPED": "Stopped",
        //PMA - END CODE - 2017-01-16 - New UK Button
        "PP_BTN_AUDITTRAIL": "Audit Trail",
        "PP_LBL_TACTICS": "Tactics", //Missing
        'PP_BTN_MANAGE_FUND': 'Manage Funds',
        'PP_BTN_APPLY_FUND': 'Apply Fund',
        'PP_BTN_ENDDATE': 'End Date',
        //API - START - TPM-1499 - New SoCo Layout
        'PP_LBL_MAIN_ID': 'Promotion ID',
        'PP_LBL_MAIN_DETAILS': 'Promotion Details',
        'PP_LBL_MAIN_DATES': 'Promotion Dates',
        //API - END - TPM-1499 - New SoCo Layout
        //API - START - TPM-1771 - Close Button for SoCo
        'PP_BTN_CLOSE': 'Close',
        //API - END - TPM-1771
        //API - START - TPM-XXX - New Tactic Layout
        'PP_TIT_TACTIC_DETAILS': 'Tactic Details',
        'PP_TIT_TACTIC_DATES': 'Tactic Dates',
        //API - END
        //PMA - START CODE - TPM-1498 - Audit Trail
        'PP_LBL_PROMOTIONHISTORY_NAME': 'Name',
        'PP_LBL_PROMOTIONHISTORY_CREATEDDATE': 'Created Date',
        'PP_LBL_PROMOTIONHISTORY_NEWVALUE': 'New Value',
        'PP_LBL_PROMOTIONHISTORY_OLDVALUE': 'Old Value',
        'PP_LBL_PROMOTIONHISTORY_TITLE': 'Audit Trail'
        //PMA - END CODE - TPM-1498 - Audit Trail */
    }
};

module.exports = Localization;
