var loFilteredProductsMock = {
    read: function (promotionId) {
        var result = {
            '__Model': 'LOFilteredProducts',
            '__Status': true,
            'data': [
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'Dummy'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'Dummy'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': '*Crispy Diet Cream Wafer',
                    'Id': 'a0d61000000OEAXAA1',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': 'pk',
                    'Pack_Size__c': 6,
                    'Short_Description__c': 'Diet Cream Wafer',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Another product 2',
                    'Id': 'a0d61000000OEAXAA2',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer2',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'Yet another product',
                    'Id': 'a0d61000000OEAXAA3',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                },
                {
                    'Category__c': 'Snacks',
                    'Container_Size_Unit__c': null,
                    'Container_Size__c': null,
                    'Container_Type__c': null,
                    'Criterion_3_Product_Code__c': 'a1D36000001z7Rc',
                    'Criterion_3_Product_Description__c': 'Brand 1',
                    'Description_1__c': 'The last one',
                    'Id': 'a0d61000000OEAXAA4',
                    'Name': 'a0d61000000OEAX',
                    'Pack_Size_Unit__c': null,
                    'Pack_Size__c': null,
                    'Short_Description__c': 'Diet Cream Wafer3',
                    UL_Material_Type__c: 'AL'
                }
            ]
        };

        return result;
    }
};

module.exports = loFilteredProductsMock;
