/*****************************************************************************************************************************
@Author :Cognizant
@name : AF_CheckRecursivePOReport
@CreateDate : 21/6/2014
@Description : This is class used to stop recursion for AF_Populate_Po_Report_Trigger trigger and AF_PO_ReportHandler class
@        
@Version : 1.0
@reference : none
***********************************************************************************/
public class AF_CheckRecursivePOReport
{
	public static boolean run=true;
}