public class Amr_ConstantForAdManager{


     // Amr_RAPJobPortfolioController_Test constants
     public static final String LOCALSIDEKEY= 'en_US';
     public static final String TESTCOUNTRY= 'testcountry';
     public static final String TESTEMAIL= 'abc@gmail.com';

     // Amr_CAPJobPortfolioController_CC constants
     public static final String DATEFORMAT = 'yyyy-MM-dd\'T\'hh:mm:ss\'Z\'';
     public static final String SECDATEFORMAT = 'yyyy-MM-dd\'T\'HH:mm:ss\'Z\'';
    
    
     public static final String YES = 'yes';
     public static final String EMAIL = 'abc@gmail.com';
     public static final String BRODCAST = 'broadMarket';
     public static final String CLUSTER = 'africa12';
     public static final String LOCATION = 'leadCon12';
     public static final String BB = 'BB';
     public static final String EXECUTION = 'testEx';
     public static final String TYPEPROD = 'testActivityAb';
     //public static final String CLUSTER = 'testClusterAb';
     public static final String PRIORITY = 'Priority';
     public static final boolean TRUE_VAL = true; 
     public static final boolean FALSE_VAL = false;
     public static final String NONE = '--None--';
     public static final String PROJECT = 'testProj';
     
     public static final String TESTCAMPAINGNAME = 'testcampaign';
     public static final String TESTALIAS = 'selUsr';
     public static final String ENCODINGTYPE = 'UTF-8';
     public static final String ZONEKEY = 'America/Los_Angeles';
     public static final String TESTLASTNAME = 'selectedTesting21';
     public static final String TESTUSERNAME = 'selectedUserr@org.com';
     public static final String TESTPROJECTNAME = 'testProject';
     public static final String TESTNAME = 'testName';
     public static final String TESTCATEGORY = 'testCat';
     public static final String TESTBRANDPOSITION = 'testBrandPos';
     public static final String TESTBRANDNAME = 'testBrand';
     public static final String TESTCOUNTRYNAME = 'testCountry';
     public static final String JOBSHEETLOCATION = 'Page.Amr_Jobsheet';
     public static final String TESTUNITCURRENCY = 'testUnit';
     public static final String TESTCAMPAING = 'testUnit';
     public static final String TESTEXECUTIONNAME = 'testUnit';
     public static final String  SLASH = '\'';
     public static final String  PERCENTAGESLASH = '%\'';
     public static final String  PERCENTAGE = '%';
     public static final String  COMMA = ',';
     public static final String  SINGLE_QUOTE = '';
     public static final String TESTAGENCY = 'testAgency';
     public static final String TEST = 'test';
     public static final String TESTCLUSTER = 'testCluster';
     public static final String TESTMARKET = 'testMarket';
     public static final String TESTPROJECT = 'testProj';
     public static final String BROADMARKET='broadMarket';
     public static final String TESTSTAGE = 'testStage';
     public static final String NO='no';
     public static final String ID='id';
     public static final String EMAILADDR ='abc@gmail.com';
     public static final string TESTACTIVITY = 'testActivity';
     
     //admanager constants
     public static final string USA_US ='USA-US $';
     public static final string UK ='UK-£';
     public static final string EEC_EURO ='EEC-Euro';
     public static final string DASH = '-';
     public static final string FILL_INFO ='Please fill in missing information';
     public static final string RAP = 'RAP';
     public static final string NINTY_SERIES ='99999';
     public static final string ZERO_SERIES ='00001';
     public static final string BACK_SLASH ='/';
     public static final string EDIT ='Edit';
     public static final string ZERO ='0';
    
    
     //submitted saving
     public static final string ATTACHMENT_ADDED = 'Attachment added';
    
     //jobsheet test constant
     public static final String ADNumber='ABC/00001';
     public static final String ADNum='ABC/00003';
     public static final String PENDING = 'Pending';
     
     public static final String LIVE = 'Live';
     public static final String DORMANT = 'Dormant';
     public static final String SELECTEDCOUNTRY = 'selectedCountry';
     public static final String USAUS = 'USA-US $';
     //public static final String UK ='UK-£';
     public static final String EECEuro ='EEC-Euro';
     public static final String  READ = 'Read';
     public static final String  CLUSTERLA= 'latin america';
     public static final String AMR_REPORT = 'Amr_Report';
     public static final String STAGE_ONEANDTWOCOUNT = 'stageOneandTwoCount';
     public static final String ALL_COUNT = 'allCount';
     public static final String CREATED_DATE =  ' and AM_Job_Detail__r.createdDate ';
     public static final String SFOBJECTSUFFIX = '__c';
     
   
}