public class IPM_ConstantUtils {
    public Static String DUPLICATE_EXCEPTION='DUPLICATE_VALUE';
    public static String ROLLOUT_LEADER = 'Leader';
    public static String ROLLOUT_Follower = 'Follower';
    
    public static String PROJECT_LEADER = 'Project Leader';
    
    public static String STATUS_EXCLUDED = 'Excluded';
    public static String STATUS_NOT_STARTED = 'Not Started';
    public static String STATUS_NOT_FILLED = 'Filled-in';
    public static String STATUS_APPROVED = 'Approved';
    public static String PD_STATUS_STOPPED = 'Stopped';
}