public class VPM_MaintainVendorFieldDetailsWrapper {
    
    public Integer RequestNumber {get; set;}
    public string RequestorName {get; set;}
    public string RequestorPhone {get; set;}
    public string RequestorEmail {get; set;}
    public string requestorCountry {get; set;}
    public string mdmBPMRequestorDepartment {get; set;}
    public string originatorEmail {get; set;}
    public string RequestDate {get; set;}
    public string VendorNumber {get; set;}
    
    //vendor code
    public string vendorCode {get; set;}
    public string vendorName1c {get; set;}
    public string mdmBpmComments {get; set;}
    //VPM_ECCSystem
    public string extendRegion {get; set;}
    public string vendorName1 {get; set;}
    public string vendorName12 {get; set;}
    public string vendorName3 {get; set;}
    public string vendorName4 {get; set;}
    public string searchTerm1 {get; set;}
    public string searchTerm2 {get; set;}
    
    public string Street1 {get; set;}
    public string Street2 {get; set;}
    public string Street3 {get; set;}
    public string Street4 {get; set;}
    public string houseNumber {get; set;}
    public string houseNumberSupplement {get; set;}
    
    public string zipPostCode {get; set;}
    public string region {get; set;}
    public string country {get; set;}
    public string city {get; set;}
    public string district {get; set;}
    
    public string isVendorSME {get; set;}
    public string isVendorException {get; set;}
    public string exceptionType {get; set;}
    
    public string poBox {get; set;}
    public string poBoxPostCode {get; set;}
    
    public string taxNumber1 {get; set;}
    public string taxNumber2 {get; set;}
    public string taxNumber3 {get; set;}
    public string taxNumber4 {get; set;}
    public string vatRegistrationNumber {get; set;}
    public string isNaturalPerson {get; set;}
    public string taxNumberType {get; set;}
    public string taxJurisdictionCode {get; set;}
    public string taxNumAtResponsibleTaxAuthority {get; set;}
    
    public string creditInfoNumber {get; set;}
    public string corporateGrp {get; set;}
    public string intLocationNumber1 {get; set;}
    public string intLocationNumber2 {get; set;}
    public string extManufacturer {get; set;}
    public string checkDigit {get; set;}
    
}