var Localization = {
    'labels': {
        "PP_BTN_SEARCH": "Search",
        "PP_BTN_EDIT": "Edit",
        "PP_LBL_TACTIC": "Tactic",
        "PP_BTN_DUPLICATE": "Duplicate",
        "PP_BTN_DELETE": "Delete",
        "PP_BTN_SAVE_REFRESH": "Save & Refresh",
        "PP_BTN_DONE": "Done",
        "PP_BTN_CANCEL": "Cancel",
        "PP_BTN_OK": "Ok",
        "PP_BTN_ADD": "Add",
        "PP_TIT_PROD_LOOKUP": "Product Lookup",
        //"PP_LBL_TACTIC_NAME": "Tactic Name",
        //"PP_LBL_PCT_STORES": "% Stores",
        //"PP_LBL_LIFT": "Lift %",
        //"PP_LBL_AMOUNT": "Amount",
        //"PP_LBL_COST_METHOD": "Costing Method",
        "PP_LBL_NODATA": "No data",
        "PP_TIT_KPI": "KPIs",
        "PP_TIT_MEASURE": "Measure",
        "PP_LBL_PLANNED": "Planned",
        "PP_TIT_CHART_VOLUME_VS_BASELINE": "Planned Tactic Volume vs. Baseline",
        "PP_TIT_CHART_INCREMENTAL_COSTS": "Incremental Costs (Tactic)",
        "PP_TIT_CHART_INCREMENTAL_SALES": "Incremental Sales (Tactic)",
        "PP_TIT_CHART_ROI": "ROI",
        "PP_TIT_CHART_COSTS": "COSTS",
        "PP_TIT_NOCONTENT": "NO CONTENT",
        "PP_LBL_MAIN_INFO": "Main Information",
        "PP_LBL_DATES": "Dates",
        "PP_LBL_DURATION": "Duration",
        "PP_LBL_STATUS": "Status",
        "PP_BTN_APPLY_FILTER": "Apply Filter",
        "PP_TIT_TACTIC_INFO": "Tactic Information",
        "PP_BTN_MANAGE_PRODS": "Manage Products",
        "PP_TIT_PROMO_SUMMARY": "Promotion Summary",
        "PP_LBL_NO_FUNDS": "No Funds associated to this tactic",
        "PP_TIT_FUND_LOOKUP": "Fund Lookup",
        //"PP_LBL_TACTICS": "Tactics", //Missing
        "PP_LBL_PRODUCT_GROUPS": "Product Groups",
        "PP_LBL_PRODUCTS": "Products",
        "PP_LBL_SELECT": "Select",
        "PP_LBL_INCLUDED": "Included"
        /*,
        "PP_LBL_MODAL_MSG": "Sit nulla est ex deserunt exercitation anim occaecat. Nostrud ullamco deserunt aute id consequat veniam incididunt duis in sint irure nisi.",
        "PC_TIT_EDIT_SETTINGS": "Edit your Settings",
        "PC_BTN_CONTINUE": "Continue anyways",
        "PC_BTN_SAVE": "Save",
        "PC_TIT_TRADE_CALENDAR": "Trade calendar",
        "PC_LBL_INIT_CALENDAR_MSG_1": "Hi, your user settings haven\"t completed yet. ",
        "PC_LBL_INIT_CALENDAR_MSG_2": " To avoid longer loading times, please fill them in before you continue.",
        "PC_LBL_CUSTOMER": "Customer",
        "PC_LBL_CUSTOMER_NAME": "Customer name",
        "PC_LBL_ANCHOR_CUSTOMER": "Anchor Customer",
        "PC_LBL_ANCHOR_CUSTOMER_SET": "Anchor Customer Set",
        "PC_LBL_PROMOTION_TYPE": "Promotion type",
        "PC_LBL_PROMOTION_TEMPLATE": "Promotion Template",
        "PC_LBL_PRODUCT_CATEGORY": "Product category",
        "PC_LBL_TACTIC_TYPE": "Tactic type",
        "PC_LBL_NEW": "New ",
        "PC_LBL_LOADING_CONTENT": "Loading content...",
        "PC_LBL_FROM_THRU": "FROM/THRU",
        "PC_LBL_STATUS": "STATUS",
        "PC_LBL_ANCHOR": "ANCHOR",
        "PC_LBL_TACTICS_FROM_THRU": "TACTICS FROM/THRU",
        "PC_BTN_OPEN": "Open",
        "PC_BTN_DERIVE": "Derive",
        "PC_BTN_DELETE": "Delete",
        "PC_LBL_JANUARY": "January",
        "PC_LBL_FEBRUARY": "February",
        "PC_LBL_MARCH": "March",
        "PC_LBL_APRIL": "April",
        "PC_LBL_MAY": "May",
        "PC_LBL_JUNE": "June",
        "PC_LBL_JULY": "July",
        "PC_LBL_AUGUST": "August",
        "PC_LBL_SEPTEMBER": "September",
        "PC_LBL_OCTOBER": "October",
        "PC_LBL_NOVEMBER": "November",
        "PC_LBL_DECEMBER": "December",
        "PC_TIT_ACCOUNTS": "Accounts",
        "PC_TIT_PROMOTIONS": "Promotions",
        "PC_TIT_PRODUCTS": "Products",
        "PC_BTN_ADD_FILTER": "Add Filter",
        "PC_LBL_FIELD": "Field",
        "PC_LBL_VALUE": "Value",
        "PC_LBL_VALUES_SELECTED": "values selected",
        "PC_LBL_FILTERS": "Filters",
        "PC_LBL_DAYS": "Days",
        "PC_LBL_WEEKS": "Weeks",
        "PC_LBL_MONTHS": "Months",
        "PC_LBL_SLOGAN": "Slogan",
        "PC_LBL_START": "Start",
        "PC_LBL_TEMPLATE": "Template",
        "PC_LBL_SELECT": "Select"*/
    },
    'dateformats': {
        "ar-SA": "DD/MM/yy",
        "bg-BG": "DD.M.YYYY",
        "ca-ES": "DD/MM/YYYY",
        "zh-TW": "YYYY/M/d",
        "cs-CZ": "DD.M.YYYY",
        "da-DK": "DD-MM-YYYY",
        "de-DE": "DD.MM.YYYY",
        "el-GR": "DD/M/YYYY",
        "en-US": "MM/DD/YYYY",
        "fi-FI": "DD.M.YYYY",
        "fr-FR": "DD/MM/YYYY",
        "he-IL": "DD/MM/YYYY",
        "hu-HU": "YYYY. MM. DD.",
        "is-IS": "DD.M.YYYY",
        "it-IT": "DD/MM/YYYY",
        "ja-JP": "YYYY/MM/DD",
        "ko-KR": "YYYY-MM-DD",
        "nl-NL": "d-M-YYYY",
        "nb-NO": "DD.MM.YYYY",
        "pl-PL": "YYYY-MM-DD",
        "pt-BR": "DD/M/YYYY",
        "ro-RO": "DD.MM.YYYY",
        "ru-RU": "DD.MM.YYYY",
        "hr-HR": "DD.M.YYYY",
        "sk-SK": "DD. M. YYYY",
        "sq-AL": "YYYY-MM-DD",
        "sv-SE": "YYYY-MM-DD",
        "th-TH": "DD/M/YYYY",
        "tr-TR": "DD.MM.YYYY",
        "ur-PK": "DD/MM/YYYY",
        "id-ID": "DD/MM/YYYY",
        "uk-UA": "DD.MM.YYYY",
        "be-BY": "DD.MM.YYYY",
        "sl-SI": "DD.M.YYYY",
        "et-EE": "DD.MM.YYYY",
        "lv-LV": "YYYY.MM.DD.",
        "lt-LT": "YYYY.MM.DD",
        "fa-IR": "MM/DD/YYYY",
        "vi-VN": "DD/MM/YYYY",
        "hy-AM": "DD.MM.YYYY",
        "az-Latn-AZ": "DD.MM.YYYY",
        "eu-ES": "YYYY/MM/DD",
        "mk-MK": "DD.MM.YYYY",
        "af-ZA": "YYYY/MM/DD",
        "ka-GE": "DD.MM.YYYY",
        "fo-FO": "DD-MM-YYYY",
        "hi-IN": "DD-MM-YYYY",
        "ms-MY": "DD/MM/YYYY",
        "kk-KZ": "DD.MM.YYYY",
        "ky-KG": "DD.MM.yy",
        "sw-KE": "MM/DD/YYYY",
        "uz-Latn-UZ": "DD/MM YYYY",
        "tt-RU": "DD.MM.YYYY",
        "pa-IN": "DD-MM-yy",
        "gu-IN": "DD-MM-yy",
        "ta-IN": "DD-MM-YYYY",
        "te-IN": "DD-MM-yy",
        "kn-IN": "DD-MM-yy",
        "mr-IN": "DD-MM-YYYY",
        "sa-IN": "DD-MM-YYYY",
        "mn-MN": "yy.MM.DD",
        "gl-ES": "DD/MM/yy",
        "kok-IN": "DD-MM-YYYY",
        "syr-SY": "DD/MM/YYYY",
        "dv-MV": "DD/MM/yy",
        "ar-IQ": "DD/MM/YYYY",
        "zh-CN": "YYYY/M/d",
        "de-CH": "DD.MM.YYYY",
        "en-GB": "DD/MM/YYYY",
        "es-MX": "DD/MM/YYYY",
        "fr-BE": "DD/MM/YYYY",
        "it-CH": "DD.MM.YYYY",
        "nl-BE": "DD/MM/YYYY",
        "nn-NO": "DD.MM.YYYY",
        "pt-PT": "DD-MM-YYYY",
        "sr-Latn-CS": "DD.M.YYYY",
        "sv-FI": "DD.M.YYYY",
        "az-Cyrl-AZ": "DD.MM.YYYY",
        "ms-BN": "DD/MM/YYYY",
        "uz-Cyrl-UZ": "DD.MM.YYYY",
        "ar-EG": "DD/MM/YYYY",
        "zh-HK": "DD/M/YYYY",
        "de-AT": "DD.MM.YYYY",
        "en-AU": "DD/MM/YYYY",
        "es-ES": "DD/MM/YYYY",
        "fr-CA": "YYYY-MM-DD",
        "sr-Cyrl-CS": "DD.M.YYYY",
        "ar-LY": "DD/MM/YYYY",
        "zh-SG": "DD/M/YYYY",
        "de-LU": "DD.MM.YYYY",
        "en-CA": "DD/MM/YYYY",
        "es-GT": "DD/MM/YYYY",
        "fr-CH": "DD.MM.YYYY",
        "ar-DZ": "DD-MM-YYYY",
        "zh-MO": "DD/M/YYYY",
        "de-LI": "DD.MM.YYYY",
        "en-NZ": "DD/MM/YYYY",
        "es-CR": "DD/MM/YYYY",
        "fr-LU": "DD/MM/YYYY",
        "ar-MA": "DD-MM-YYYY",
        "en-IE": "DD/MM/YYYY",
        "es-PA": "MM/DD/YYYY",
        "fr-MC": "DD/MM/YYYY",
        "ar-TN": "DD-MM-YYYY",
        "en-ZA": "YYYY/MM/DD",
        "es-DO": "DD/MM/YYYY",
        "ar-OM": "DD/MM/YYYY",
        "en-JM": "DD/MM/YYYY",
        "es-VE": "DD/MM/YYYY",
        "ar-YE": "DD/MM/YYYY",
        "en-029": "MM/DD/YYYY",
        "es-CO": "DD/MM/YYYY",
        "ar-SY": "DD/MM/YYYY",
        "en-BZ": "DD/MM/YYYY",
        "es-PE": "DD/MM/YYYY",
        "ar-JO": "DD/MM/YYYY",
        "en-TT": "DD/MM/YYYY",
        "es-AR": "DD/MM/YYYY",
        "ar-LB": "DD/MM/YYYY",
        "en-ZW": "MM/DD/YYYY",
        "es-EC": "DD/MM/YYYY",
        "ar-KW": "DD/MM/YYYY",
        "en-PH": "MM/DD/YYYY",
        "es-CL": "DD-MM-YYYY",
        "ar-AE": "DD/MM/YYYY",
        "es-UY": "DD/MM/YYYY",
        "ar-BH": "DD/MM/YYYY",
        "es-PY": "DD/MM/YYYY",
        "ar-QA": "DD/MM/YYYY",
        "es-BO": "DD/MM/YYYY",
        "es-SV": "DD/MM/YYYY",
        "es-HN": "DD/MM/YYYY",
        "es-NI": "DD/MM/YYYY",
        "es-PR": "DD/MM/YYYY",
        "am-ET": "DD/M/YYYY",
        "tzm-Latn-DZ": "DD-MM-YYYY",
        "iu-Latn-CA": "DD/MM/YYYY",
        "sma-NO": "DD.MM.YYYY",
        "mn-Mong-CN": "YYYY/M/d",
        "gd-GB": "DD/MM/YYYY",
        "en-MY": "DD/M/YYYY",
        "prs-AF": "DD/MM/yy",
        "bn-BD": "DD-MM-yy",
        "wo-SN": "DD/MM/YYYY",
        "rw-RW": "MM/DD/YYYY",
        "qut-GT": "DD/MM/YYYY",
        "sah-RU": "MM.DD.YYYY",
        "gsw-FR": "DD/MM/YYYY",
        "co-FR": "DD/MM/YYYY",
        "oc-FR": "DD/MM/YYYY",
        "mi-NZ": "DD/MM/YYYY",
        "ga-IE": "DD/MM/YYYY",
        "se-SE": "YYYY-MM-DD",
        "br-FR": "DD/MM/YYYY",
        "smn-FI": "DD.M.YYYY",
        "moh-CA": "MM/DD/YYYY",
        "arn-CL": "DD-MM-YYYY",
        "ii-CN": "YYYY/M/d",
        "dsb-DE": "DD. M. YYYY",
        "ig-NG": "DD/M/YYYY",
        "kl-GL": "DD-MM-YYYY",
        "lb-LU": "DD/MM/YYYY",
        "ba-RU": "DD.MM.yy",
        "nso-ZA": "YYYY/MM/DD",
        "quz-BO": "DD/MM/YYYY",
        "yo-NG": "DD/M/YYYY",
        "ha-Latn-NG": "DD/M/YYYY",
        "fil-PH": "MM/DD/YYYY",
        "ps-AF": "DD/MM/yy",
        "fy-NL": "d-M-YYYY",
        "ne-NP": "MM/DD/YYYY",
        "se-NO": "DD.MM.YYYY",
        "iu-Cans-CA": "DD/M/YYYY",
        "sr-Latn-RS": "DD.M.YYYY",
        "si-LK": "YYYY-MM-DD",
        "sr-Cyrl-RS": "DD.M.YYYY",
        "lo-LA": "DD/MM/YYYY",
        "km-KH": "YYYY-MM-DD",
        "cy-GB": "DD/MM/YYYY",
        "bo-CN": "YYYY/M/d",
        "sms-FI": "DD.M.YYYY",
        "as-IN": "DD-MM-YYYY",
        "ml-IN": "DD-MM-yy",
        "en-IN": "DD-MM-YYYY",
        "or-IN": "DD-MM-yy",
        "bn-IN": "DD-MM-yy",
        "tk-TM": "DD.MM.yy",
        "bs-Latn-BA": "DD.M.YYYY",
        "mt-MT": "DD/MM/YYYY",
        "sr-Cyrl-ME": "DD.M.YYYY",
        "se-FI": "DD.M.YYYY",
        "zu-ZA": "YYYY/MM/DD",
        "xh-ZA": "YYYY/MM/DD",
        "tn-ZA": "YYYY/MM/DD",
        "hsb-DE": "DD. M. YYYY",
        "bs-Cyrl-BA": "DD.M.YYYY",
        "tg-Cyrl-TJ": "DD.MM.yy",
        "sr-Latn-BA": "DD.M.YYYY",
        "smj-NO": "DD.MM.YYYY",
        "rm-CH": "DD/MM/YYYY",
        "smj-SE": "YYYY-MM-DD",
        "quz-EC": "DD/MM/YYYY",
        "quz-PE": "DD/MM/YYYY",
        "hr-BA": "DD.M.YYYY.",
        "sr-Latn-ME": "DD.M.YYYY",
        "sma-SE": "YYYY-MM-DD",
        "en-SG": "DD/M/YYYY",
        "ug-CN": "YYYY-M-d",
        "sr-Cyrl-BA": "DD.M.YYYY",
        "es-US": "MM/DD/YYYY"
    }
};

module.exports = Localization;


