<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst count="62" uniqueCount="33" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
        <si>
            <t>INNOVATION YEARS</t>
        </si>
        <si>
            <t>GROSS PL</t>
        </si>
        <si>
            <t>INCREMENTAL PL</t>
        </si>
        <si>
            <t>Y0</t>
        </si>
        <si>
            <t>Y1</t>
        </si>
        <si>
            <t>Y2</t>
        </si>
        <si>
            <t>Y3</t>
        </si>
        <si>
            <t>Value Market Share</t>
        </si>
        <si>
            <t>%</t>
        </si>
        <si>
            <t>Volume</t>
        </si>
        <si>
            <t>+</t>
        </si>
        <si>
            <t>Turnover</t>
        </si>
        <si>
            <t>€ '000</t>
        </si>
        <si>
            <t>Gross Profit</t>
        </si>
        <si>
            <t>Advertising Promotions</t>
        </si>
        <si>
            <t>-</t>
        </si>
        <si>
            <t>Profit Before Overheads</t>
        </si>
        <si>
            <t>NPV</t>
        </si>
        <si>
            <t>CAPEX</t>
        </si>
        <si>
            <t>IRR</t>
        </si>
        <si>
            <t>BIC</t>
        </si>
        <si>
            <t>Payback</t>
        </si>
        <si>
            <t>Years</t>
        </si>
        <si>
            <t>CALENDAR YEARS</t>
        </si>
        <si>
            <t>Total Tons</t>
        </si>
        <si>
            <r>
                <t xml:space="preserve">This is a system generated sheet for auto-uploading business case outputs per country/MCO inIPM-NG, 
                Please update per Country/MCO financials in the </t>
            </r>
            <r>
                <rPr>
                    <b></b>
                    <sz val="11"></sz>
                    <color theme="1"></color>
                    <rFont val="Calibri"></rFont>
                    <family val="2"></family>
                    <scheme val="minor"></scheme>
                </rPr>
                <t xml:space="preserve">ORANGE CELLS</t>
            </r>
            <r>
                <rPr>
                    <sz val="11"></sz>
                    <color theme="1"></color>
                    <rFont val="Calibri"></rFont>
                    <family val="2"></family>
                    <scheme val="minor"></scheme>
                </rPr>
                <t xml:space="preserve"> ONLY DO NOT insert new rows/columns OR modify any other field on this sheet</t>
            </r>
        </si>
        <si>
            <t>Project Name</t>
        </si>
        <si>
            <t>DEF1153BLOC</t>
        </si>
        <si>
            <t>Currency</t>
        </si>
        <si>
            <t>EUR</t>
        </si>
        <si>
            <t>Project Id</t>
        </si>
        <si>
            <t>DEF1153BLOC_SEAA_ANZ</t>
        </si>
        <si>
            <t>a0QL0000002GmeLMAS</t>
        </si>
            <si>
                <t>DEF1153BLOC_EUR_NONKEY</t>
            </si>
    </sst>